site_name: OMI glTF Extensions
docs_dir: extensions/2.0
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      accent: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
use_directory_urls: true
nav:
  - Home: index.md
  - KHR_audio_emitter: KHR_audio_emitter/README.md
  - OMI_audio_ogg_vorbis: OMI_audio_ogg_vorbis/README.md
  - OMI_audio_opus: OMI_audio_opus/README.md
  - OMI_link: OMI_link/README.md
  - OMI_personality: OMI_personality/README.md
  - OMI_physics_body:
    - Overview: OMI_physics_body/README.md
    - Collider: OMI_physics_body/README.collider.md
    - Motion: OMI_physics_body/README.motion.md
    - Trigger: OMI_physics_body/README.trigger.md
  - OMI_physics_gravity: OMI_physics_gravity/README.md
  - OMI_physics_joint: OMI_physics_joint/README.md
  - OMI_physics_shape: OMI_physics_shape/README.md
  - OMI_seat: OMI_seat/README.md
  - OMI_spawn_point: OMI_spawn_point/README.md
  - Archived:
    - OMI_collider: Archived/OMI_collider/README.md
