name: Run posters script

on:
  schedule:
    - cron: '59 23 * * 4' # Run every Thursday near midnight

jobs:
  run_posters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run posters script on Thursday
        if: github.event.schedule.cron == '59 23 * * 4'
        run: |
          chmod +x extensions/2.0/readmes.sh
          ./extensions/2.0/readmes.sh
          git config --global user.name "madjin"
          git config --global user.email "32600939+madjin@users.noreply.github.com"
          git add -A .
          git commit -m "Run action runner"
          git push origin main
