name: Update posters

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update READMEs
      run: |
        cd extensions/2.0/
        chmod +x readmes.sh
        ./readmes.sh
    - name: Commit changes
      run: |
        git config --global user.name "madjin"
        git config --global user.email "32600939+madjin@users.noreply.github.com"
        git add .
        git commit -m "Update READMEs"
        git push
